
sensor:
  # https://esphome.io/components/sensor/bme280.html
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      id: bme_temp
    pressure:
      name: "BME280 Pressure"
      id: bme_pressure
    humidity:
      name: "BME280 Humidity"
      id: bme_humidity
