sensor:
  # https://esphome.io/components/sensor/bme280.html
  - platform: bme280_i2c
    address: 0x76
    temperature:
      name: "BME280 Temperature"
      id: temp_raw
      internal: true
    pressure:
      name: "BME280 Pressure"
      id: pressure_raw
      internal: true
    humidity:
      name: "BME280 Humidity"
      id: humidity_raw
      internal: true

  - platform: copy
    source_id: temp_raw
    name: "Temperature"
    id: temp
    # https://www.airgradient.com/documentation/correction-algorithms/
    # No current correction for indoor devices, but structure in place if developed

  - platform: copy
    source_id: humidity_raw
    name: "Humidity"
    id: humidity
    # https://www.airgradient.com/documentation/correction-algorithms/
    # No current correction for indoor devices, but structure in place if developed

  - platform: copy
    source_id: pressure_raw
    name: "Pressure"
    id: pressure
    # https://www.airgradient.com/documentation/correction-algorithms/
    # No current correction for indoor devices, but structure in place if developed
