sensor:
  # https://esphome.io/components/sensor/bme280.html
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      id: temp_raw
    pressure:
      name: "BME280 Pressure"
      id: pressure_raw
    humidity:
      name: "BME280 Humidity"
      id: humidity_raw

  - platform: copy
    source_id: bme_temp
    name: "Temperature"
    id: temp_raw
    # https://www.airgradient.com/documentation/correction-algorithms/
    # No current correction for indoor devices, but structure in place if developed

  - platform: copy
    source_id: bme_humidity
    name: "Humidity"
    id: humidity_raw
    # https://www.airgradient.com/documentation/correction-algorithms/
    # No current correction for indoor devices, but structure in place if developed
